---
- name: Setup Nomad Client
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Nomad client is installed
      homebrew:
        name: nomad
        state: present

    - name: Start Nomad client
      launchd:
        name: com.hashicorp.nomad
        state: started
        run_at_load: yes
        program: /usr/local/bin/nomad
        args:
          - agent
          - -client
          - -dev
          - -bind=127.0.0.1
